spring:
  application:
    name: Partner_back
  datasource:
    url: jdbc:mysql://localhost:3306/partner?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    #文件上传大小限制
  servlet:
    multipart:
      #最大单个文件大小S
      max-file-size: 10MB
      #最大请求大小（包括所有文件和表单数据）
      max-request-size: 100MB

server:
  port: 8080

  # MyBatis配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #    驼峰命名开关
    map-underscore-to-camel-case: true

#配置事务管理日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

#配置aliyun oss工具类信息
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: tials-smart-sys
    region: cn-beijing
#配置mybatis-plus
mybatis-plus:
  global-config:
    db-config:
#      配置mubatis-plus逻辑删除的全局配置 默认查出删除状态为未删除的数据
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)